### This Notebook is used to understand Bigrams. 
### Matrix Generation for Bigrams
### Calculating Probailibities and Log likelihood for each bigram
### This is the first Part of Char level Modeling in next part we will discuss NN Model for same
By Prof. Naveen Aggarwal

#### Lets read a text file containing names

In [1]:
words=open("names.txt", 'r').read().splitlines()

#### Lets check whether we have read the file properly. 

In [2]:
words[:10]

['emma',
 'olivia',
 'ava',
 'isabella',
 'sophia',
 'charlotte',
 'mia',
 'amelia',
 'harper',
 'evelyn']

In [3]:
len(words)

32033

##### What is maximum and minimum size of words in this file

In [4]:
min(len(w) for w in words)

2

In [5]:
max(len(w) for w in words)

15

##### Finding Bigrams: To understand it better, Lets run it on first three words 

In [6]:
for w in words [:3]:
    for ch1, ch2 in zip (w[:], w[1:]):
        print(ch1, ch2)

e m
m m
m a
o l
l i
i v
v i
i a
a v
v a


###### But we must have start and end character, Lets modified the code accordingly

In [7]:
for w in words [:1]:
    # we are adding special character at start and end of each word
    ws=["<S>"] + list(w) + ["<E>"]
    for ch1, ch2 in zip (ws[:], ws[1:]):
        print(ch1, ch2)

<S> e
e m
m m
m a
a <E>


#### Now we are able to generate bigrams, So we have to do it for full set of words. Rather than printing , we can add them into a dictionary

In [8]:
b={}
for w in words [:4]:
    # we are adding special character at start and end of each word
    ws=["<S>"] + list(w) + ["<E>"]
    for ch1, ch2 in zip (ws[:], ws[1:]):
        # Make a Tuple of selected Ch1 and ch2
        bigram=(ch1,ch2)
        # Add into the dictionary, b.get gives count if bigram is already in dictionary otherwise zero
        b[bigram]=b.get(bigram,0)+1
print(b)

{('<S>', 'e'): 1, ('e', 'm'): 1, ('m', 'm'): 1, ('m', 'a'): 1, ('a', '<E>'): 4, ('<S>', 'o'): 1, ('o', 'l'): 1, ('l', 'i'): 1, ('i', 'v'): 1, ('v', 'i'): 1, ('i', 'a'): 1, ('<S>', 'a'): 1, ('a', 'v'): 1, ('v', 'a'): 1, ('<S>', 'i'): 1, ('i', 's'): 1, ('s', 'a'): 1, ('a', 'b'): 1, ('b', 'e'): 1, ('e', 'l'): 1, ('l', 'l'): 1, ('l', 'a'): 1}


##### Now Lets Run the code for all the words

In [9]:
b={}
for w in words [:]:
    ws=["<S>"] + list(w) + ["<E>"]
    for ch1, ch2 in zip (ws[:], ws[1:]):
        bigram=(ch1,ch2)
        b[bigram]=b.get(bigram,0)+1

#### Now Lets check which bigram occur frequently

In [10]:
sorted (b.items(), key=lambda kv:kv[-1] )

[(('q', 'r'), 1),
 (('d', 'z'), 1),
 (('p', 'j'), 1),
 (('q', 'l'), 1),
 (('p', 'f'), 1),
 (('q', 'e'), 1),
 (('b', 'c'), 1),
 (('c', 'd'), 1),
 (('m', 'f'), 1),
 (('p', 'n'), 1),
 (('w', 'b'), 1),
 (('p', 'c'), 1),
 (('h', 'p'), 1),
 (('f', 'h'), 1),
 (('b', 'j'), 1),
 (('f', 'g'), 1),
 (('z', 'g'), 1),
 (('c', 'p'), 1),
 (('p', 'k'), 1),
 (('p', 'm'), 1),
 (('x', 'n'), 1),
 (('s', 'q'), 1),
 (('k', 'f'), 1),
 (('m', 'k'), 1),
 (('x', 'h'), 1),
 (('g', 'f'), 1),
 (('v', 'b'), 1),
 (('j', 'p'), 1),
 (('g', 'z'), 1),
 (('v', 'd'), 1),
 (('d', 'b'), 1),
 (('v', 'h'), 1),
 (('h', 'h'), 1),
 (('g', 'v'), 1),
 (('d', 'q'), 1),
 (('x', 'b'), 1),
 (('w', 'z'), 1),
 (('h', 'q'), 1),
 (('j', 'b'), 1),
 (('x', 'm'), 1),
 (('w', 'g'), 1),
 (('t', 'b'), 1),
 (('z', 'x'), 1),
 (('p', 'b'), 2),
 (('t', 'g'), 2),
 (('q', 's'), 2),
 (('t', 'x'), 2),
 (('f', 'k'), 2),
 (('b', 't'), 2),
 (('j', 'n'), 2),
 (('k', 'c'), 2),
 (('z', 'k'), 2),
 (('s', 'j'), 2),
 (('s', 'f'), 2),
 (('z', 'j'), 2),
 (('n', 'q

In [11]:
sorted (b.items(), key=lambda kv:-kv[1] )

[(('n', '<E>'), 6763),
 (('a', '<E>'), 6640),
 (('a', 'n'), 5438),
 (('<S>', 'a'), 4410),
 (('e', '<E>'), 3983),
 (('a', 'r'), 3264),
 (('e', 'l'), 3248),
 (('r', 'i'), 3033),
 (('n', 'a'), 2977),
 (('<S>', 'k'), 2963),
 (('l', 'e'), 2921),
 (('e', 'n'), 2675),
 (('l', 'a'), 2623),
 (('m', 'a'), 2590),
 (('<S>', 'm'), 2538),
 (('a', 'l'), 2528),
 (('i', '<E>'), 2489),
 (('l', 'i'), 2480),
 (('i', 'a'), 2445),
 (('<S>', 'j'), 2422),
 (('o', 'n'), 2411),
 (('h', '<E>'), 2409),
 (('r', 'a'), 2356),
 (('a', 'h'), 2332),
 (('h', 'a'), 2244),
 (('y', 'a'), 2143),
 (('i', 'n'), 2126),
 (('<S>', 's'), 2055),
 (('a', 'y'), 2050),
 (('y', '<E>'), 2007),
 (('e', 'r'), 1958),
 (('n', 'n'), 1906),
 (('y', 'n'), 1826),
 (('k', 'a'), 1731),
 (('n', 'i'), 1725),
 (('r', 'e'), 1697),
 (('<S>', 'd'), 1690),
 (('i', 'e'), 1653),
 (('a', 'i'), 1650),
 (('<S>', 'r'), 1639),
 (('a', 'm'), 1634),
 (('l', 'y'), 1588),
 (('<S>', 'l'), 1572),
 (('<S>', 'c'), 1542),
 (('<S>', 'e'), 1531),
 (('j', 'a'), 1473),
 (

#### Now Lets add this data into 2d Array rather than into dictionary

In [13]:
import torch

##### Lets create an array in torch. Our array will have 26 + 2 special characters

In [14]:
N=torch.zeros((28,28), dtype=torch.int32)

#### Now in Matrix, we want to give each individual alphabet a value from 0 to 25 and then start charcater=26 and end character=27

In [15]:
chars= list('abcedfghijklmnopqrstuvwxyz')
#chars

In [16]:
# We will create an enumeration
stoi={s:i for i,s in enumerate(chars)}
stoi


{'a': 0,
 'b': 1,
 'c': 2,
 'e': 3,
 'd': 4,
 'f': 5,
 'g': 6,
 'h': 7,
 'i': 8,
 'j': 9,
 'k': 10,
 'l': 11,
 'm': 12,
 'n': 13,
 'o': 14,
 'p': 15,
 'q': 16,
 'r': 17,
 's': 18,
 't': 19,
 'u': 20,
 'v': 21,
 'w': 22,
 'x': 23,
 'y': 24,
 'z': 25}

In [17]:
stoi['<S>']=26
stoi['<E>']=27

#### Now Lets create an array

In [18]:
for w in words [:]:
    ws=["<S>"] + list(w) + ["<E>"]
    for ch1, ch2 in zip (ws[:], ws[1:]):
        ix1=stoi[ch1]
        ix2=stoi[ch2]
        N[ix1,ix2]+=1

In [19]:
print(N[:3,:3])

tensor([[556, 541, 470],
        [321,  38,   1],
        [815,   0,  42]], dtype=torch.int32)


In [20]:
# Interesting is last row : All zeros because there is nothing after end charater
print(N[27,:])

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0], dtype=torch.int32)


In [21]:
# similarly 26th Columsn : All zeros because there is nothing before start charater
print(N[:, 26])

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0], dtype=torch.int32)


#### Now to deal with this lets use one token for start and end. Let it be '.' Further, we will take this as first token and give numbers to alphabets a to z from 1 to 26.

In [22]:
chars= list('.abcdefghijklmnopqrstuvwxyz')
stoi={s:i for i,s in enumerate(chars)}
stoi

# Lets also create itos, we will use later
itos={i:s for i,s in enumerate (chars)}
itos

{0: '.',
 1: 'a',
 2: 'b',
 3: 'c',
 4: 'd',
 5: 'e',
 6: 'f',
 7: 'g',
 8: 'h',
 9: 'i',
 10: 'j',
 11: 'k',
 12: 'l',
 13: 'm',
 14: 'n',
 15: 'o',
 16: 'p',
 17: 'q',
 18: 'r',
 19: 's',
 20: 't',
 21: 'u',
 22: 'v',
 23: 'w',
 24: 'x',
 25: 'y',
 26: 'z'}

In [23]:
N=torch.zeros((27,27), dtype=torch.int32)
for w in words [:]:
    ws=  ws=["."] + list(w) + ["."]
    for ch1, ch2 in zip (ws[:], ws[1:]):
        ix1=stoi[ch1]
        ix2=stoi[ch2]
        N[ix1,ix2]+=1

In [24]:
print(N[:5,:5])

tensor([[   0, 4410, 1306, 1542, 1690],
        [6640,  556,  541,  470, 1042],
        [ 114,  321,   38,    1,   65],
        [  97,  815,    0,   42,    1],
        [ 516, 1303,    1,    3,  149]], dtype=torch.int32)


#### Now Lets create  a probability distribution, Divide each term by sum of all terms

In [25]:
p=N[0].float()
p=p/p.sum()
p

tensor([0.0000, 0.1377, 0.0408, 0.0481, 0.0528, 0.0478, 0.0130, 0.0209, 0.0273,
        0.0184, 0.0756, 0.0925, 0.0491, 0.0792, 0.0358, 0.0123, 0.0161, 0.0029,
        0.0512, 0.0642, 0.0408, 0.0024, 0.0117, 0.0096, 0.0042, 0.0167, 0.0290])

##### Now lets understand, what is torch Generator: It just generae Pseudo random numbers based on a seed value

In [26]:
g=torch.Generator().manual_seed(160014)
p=torch.rand(3, generator=g)
#p
p=p/p.sum()
p

tensor([0.1006, 0.0286, 0.8708])

#### Now This can be taken as a the Probability Distribution. Based on this Probability distribution, if we generate numbers, 10% will be '0', 2% will be 1 and 87% will be 2.
Lets check it

In [27]:
torch.multinomial(p, num_samples=100, replacement= True, generator=g)

tensor([2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 0, 1, 2, 2, 2, 2, 0, 2, 2, 2,
        2, 0, 2, 2])

#### With this understanding, Now we want to extract digits from our Array N with their probability of occurance. Lets write code for that

In [43]:

g=torch.Generator().manual_seed(2147583637)
# Tosave result
out=[]
ix=0
while True:
    p=N[ix].float()
    p=p/p.sum()
    ix=torch.multinomial(p, num_samples=1, replacement= True, generator=g).item()
    out.append(itos[ix])
    if ix == 0:
        break
print(''.join(out))

# You can change the Generator seed to get different result

elami.


#### Lets create 10 such names
#### And Lets just optimize it bit by using the Broadcasting

In [60]:
# This will run faster, we will also add 1 to avoid Zero Probaility
P=(N+1).float()
P/=P.sum(1, keepdims=True)

In [61]:
for i in range(10):
    out=[]
    ix=0
    while True:
        p=P[ix]
        ix=torch.multinomial(p, num_samples=1, replacement= True, generator=g).item()
        out.append(itos[ix])
        if ix == 0:
            break
    print(''.join(out))
    

oetowa.
ji.
annces.
se.
chisleanaka.
jara.
gisle.
mavelinie.
iph.
ridyteedela.


### So Above Model is just predicting next letter based on Probability districution defined using Generator

#### Now Lets find the log likelihood of next character after each character
#### We will first calculate Probability, We will take its log.
#### We will then use negative log likelhood.

In [62]:
# Use the same code and Modify it
log_likelihood=0.0
count=0
for w in words [:3]:
    ws=  ws=["."] + list(w) + ["."]
    for ch1, ch2 in zip (ws[:], ws[1:]):
        ix1=stoi[ch1]
        ix2=stoi[ch2]
        prob=P[ix1,ix2]
        logprob=torch.log(prob)
        log_likelihood+=logprob
        count+=1
        print(f'{ch1}{ch2}: {prob:4f} {logprob:4f}')
print(f'{log_likelihood}')
# Negative Log Likelihood
nll=-log_likelihood
print(f'{nll}')
# Average negative log likelihood
print(f'{nll/count}')


.e: 0.047785 -3.041035
em: 0.037653 -3.279348
mm: 0.025341 -3.675327
ma: 0.388514 -0.945426
a.: 0.195830 -1.630506
.o: 0.012321 -4.396479
ol: 0.077880 -2.552590
li: 0.177404 -1.729324
iv: 0.015230 -4.184479
vi: 0.350769 -1.047627
ia: 0.137974 -1.980691
a.: 0.195830 -1.630506
.a: 0.137586 -1.983508
av: 0.024623 -3.704093
va: 0.247308 -1.397122
a.: 0.195830 -1.630506
-38.80856704711914
38.80856704711914
2.4255354404449463


#### We can check for few words

In [70]:
#Use the same code and Modify it
log_likelihood=0.0
count=0
# Check for Word John, and then for uncommon word xqrt
for w in ["xqrt"]:
    ws=  ws=["."] + list(w) + ["."]
    for ch1, ch2 in zip (ws[:], ws[1:]):
        ix1=stoi[ch1]
        ix2=stoi[ch2]
        prob=P[ix1,ix2]
        logprob=torch.log(prob)
        log_likelihood+=logprob
        count+=1
        print(f'{ch1}{ch2}: {prob:4f} {logprob:4f}')
print(f'{log_likelihood}')
# Negative Log Likelihood
nll=-log_likelihood
print(f'{nll}')
# Average negative log likelihood
print(f'{nll/count}')


.x: 0.004211 -5.470090
xq: 0.001381 -6.584791
qr: 0.006689 -5.007297
rt: 0.016422 -4.109147
t.: 0.086475 -2.447901
-23.619224548339844
23.619224548339844
4.7238450050354


#### Now Calculate it for all words, but do not print

In [71]:
#Use the same code and Modify it
log_likelihood=0.0
count=0
# Check for Word John, and then for uncommon word xqrt
for w in words:
    ws=  ws=["."] + list(w) + ["."]
    for ch1, ch2 in zip (ws[:], ws[1:]):
        ix1=stoi[ch1]
        ix2=stoi[ch2]
        prob=P[ix1,ix2]
        logprob=torch.log(prob)
        log_likelihood+=logprob
        count+=1
        #print(f'{ch1}{ch2}: {prob:4f} {logprob:4f}')
print(f'{log_likelihood}')
# Negative Log Likelihood
nll=-log_likelihood
print(f'{nll}')
# Average negative log likelihood
print(f'{nll/count}')

-559951.5625
559951.5625
2.4543561935424805


### Now this negative log likelihood will be used as a loss function to train NN. That will be covered in next Notebook